# path to sample sheet (TSV format, columns: sample_name, fq1 name, fq2 name)
samples: ./config/sample_sheet.tsv

# Tools paths
#fastqc: /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/fastqc-0.11.7-gcc-5.4.0-hjgfsw2
star: /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/star-2.7.2b-gcc-5.4.0-fqvrpgi
rsem: /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/rsem-1.3.1-gcc-5.4.0-ml3p6ok
# samtools: /mnt/storage/spack/share/spack/modules/linux-ubuntu16.04-x86_64/samtools-1.9-gcc-6.5.0-b2repp2
#salmon: /mnt/storage/apps/salmon-1.10.1
snakemake: /mnt/storage/apps/Mambaforge-23.1.0-1/envs/snakemake

batchCorrect: scripts/step3_batchcorrect.R

