# path to sample sheet (TSV format, columns: sample_name, fq1 name, fq2 name)
samples: ./config/sample_sheet.csv

# path to environment
conda_env: $HOME/miniforge3/bin/activate
export_path: "$HOME/miniforge3/envs/TrPLet/bin"

batchCorrect: scripts/step3_batchcorrect.R
